version: 2

jobs:

  build:
    working_directory: ~/outland-message

  docker:
    - image: circleci/openjdk:8-jdk-browsers

  environment:
    JVM_OPTS: -Xmx1G
    TERM: dumb

  steps:
    - checkout

#    - restore_cache:
#        keys:
#        - v1-dependencies-{{ checksum "build.gradle" }}
#        - v1-dependencies-
#
#    - run: curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
#    - run: unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
#    - run: echo `which protoc`
#    - run: sudo mv protoc3/bin/protoc /usr/bin/protoc
#    - run: echo `protoc --version`
#    - run: gradle dependencies
#
#    - save_cache:
#        paths:
#          - ~/.m2
#        key: v1-dependencies-{{ checksum "build.gradle" }}
#
#    - run: gradle clean test
#
#    - store_test_results:
#        path: /tmp/test-results
#

